[package]
name = "map-array-bin"
version.workspace = true
edition.workspace = true

[dependencies]
lean = { path = "../../../../lean" }
lean-sys = { path = "../../../../lean_sys" }
map-array = { path = "../map_array" }
map-array-sys = { path = "../map_array_sys" }
